name: Audit

# CI is run on pull requests and on push to the main branch
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  compilation:
    # This job is to run the tests
    name: Compile Program
    runs-on: ubuntu-latest

    env:
      ELM_HOME: '${{ github.workspace }}/elm-home'

    steps:
      # Clone the repository
      - uses: actions/checkout@v4

      # Setup Node JS
      - uses: actions/setup-node@v4

      # Install elm and cache ELM_HOME
      - name: Install Elm Tooling
        uses: mpizenberg/elm-tooling-action@v1.6
        with:
            cache-key: elm-home-${{ hashFiles('elm-tooling.json', 'elm.json') }}

      - name: Compile Main Program
        run: elm make src/Main.elm --output public/main.js

  testing:
    # This job is to run the tests
    name: Run Tests
    runs-on: ubuntu-latest

    env:
      ELM_HOME: '${{ github.workspace }}/elm-home'

    steps:
      # Clone the repository
      - uses: actions/checkout@v4

      # Setup Node JS
      - uses: actions/setup-node@v4

      # Install elm and cache ELM_HOME
      - name: Install elm
        uses: mpizenberg/elm-tooling-action@v1.6
        with:
            cache-key: elm-home-${{ hashFiles('elm-tooling.json', 'elm.json') }}

      - name: Run the tests
        run: elm-test-rs

  formatting:
    # This job is to check the formatting of files
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      # Clone the repository
      - uses: actions/checkout@v4

      # Install elm-format
      - name: Install elm-format
        uses: mpizenberg/elm-tooling-action@v1.6
        with:
            cache-key: elm-home-${{ hashFiles('elm-tooling.json', 'elm.json') }}

      - name: Check formatting
        run: elm-format --validate .